<link href="<c:url value='/css/style.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/css/jmesa.css'/>" rel="stylesheet" type="text/css">

<script type="text/javascript" src="<c:url value='/js/helper.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/calendar.js.jsp'/>"></script>
<script type="text/javascript" src="<c:url value='/js/validator.js'/>"></script>

<script type="text/javascript" src="<c:url value='/js/jquery-1.3.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery.jmesa.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jmesa.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery.validate.js'/>"></script>

